version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: php-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/api:/var/www/html
    depends_on:
      - db


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mdpro0t.
      MYSQL_DATABASE: madb
      MYSQL_USER: user
      MYSQL_PASSWORD: mdpus3r.
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: